laser_filters:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0.0    # Start angle (in radians)
        upper_angle: 3.1416 # End angle (pi radians = 180 degrees)
